spring.application.name=employeea

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/employeea
spring.datasource.username=root
spring.datasource.password=Vasanth#1422

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
